### ISSUE TITLE
Reset code not parsed correctly ?

### ISSUE THREAD

**Issue by DolphinDream** [andre-simon/ansifilter#10]
It seems that some of my terminal outputs were not parsed correctly by your app (convert to text or html) around my attribute resets code (i'm using RESET=`tput sgr0`as my reset in all my echo calls in my scripts). Somehow the reset was replaced by a "B)". As it turned out this was solved once I set my TERM to xrvt in my script. Originally my TERM was set to xterm-256color (the default with GNOME Terminal in Ubuntu 16.04). I'm not sure if this is an issue with your parsing (used for the reset codes) or your code is known to not work well with this xterm-256color.

**Comment by andre-simon** [comment]
It is very likely that this combination is not supported properly. Could you attach a file which contains the reset codes? I currently have no Ubuntu box available.

**Comment by DolphinDream** [comment]
Here are the sample files.. the terminal output itself and the filtered txt and html files.

The terminal output is generated by a script that uses both terminal colors defined by tput (see below) as well as colors generated by the git log itself. The git log colors (codes) seem to be parsed fine by your app, the problem seems to be the tput reset. As I said, by adding this: **export TERM=rxvt** to my script, the terminal output seems to be parsed correctly by your app.

`
RESET=`tput sgr0`
BOLD=`tput bold`
DIM=`tput dim`
REVERSE=`tput rev`
NORMAL="\033[21m"

BLACK=`tput setaf 0`
RED=`tput setaf 1`
GREEN=`tput setaf 2`
YELLOW=`tput setaf 3`
BLUE=`tput setaf 4`
MAGENTA=`tput setaf 5`
CYAN=`tput setaf 6`
LIGHTGRAY=`tput setaf 7`
DARKGRAY=`tput setaf 0; tput bold`
WHITE=`tput setaf 7; tput bold
`
I use these in my script like:
echo "$RED This is an error $RESET"

[sample.zip](https://github.com/andre-simon/ansifilter/files/1487891/sample.zip)

**Comment by andre-simon** [comment]
Thx for putting this together. I have committed a fix which works with your code and some other tput scripts. You might pull it and recompile or I can provide a tarball for testing.

**Comment by DolphinDream** [comment]
Yep. Seems to work fine now without setting the TERM to rxvt.

**Comment by andre-simon** [comment]
Great, I'll check if other xterm sequences need to be interpreted or ignored.
