### ISSUE TITLE
Some output is missing

### ISSUE THREAD

**Issue by agross** [andre-simon/ansifilter#12]
Hello!

I've been using anisfilter for some time to convert shell logs to HTML after I'm finished with (e.g. git) trainings. Many thanks for creating it!

I work on a Mac and use iTerm2 with [shell integration](https://www.iterm2.com/documentation-shell-integration.html) such that I can navigate easier between commands entered.

iTerm2 requires some extra escapes to be inserted in the output to be able to find the places where the user entered commands. It seems that these escapes make ansifilter omit the output. For example, the first command entered here was `man git | head`, but the HTML only contains the output of the command:

<img width="433" alt="2017-12-13_17-46-47" src="https://user-images.githubusercontent.com/16245/33950817-a19fc606-e02d-11e7-8e94-d26f85932570.png">

Here's the full log:

[ansi.log](https://github.com/andre-simon/ansifilter/files/1556295/ansi.log)

**Comment by agross** [comment]
Tracing this down further, I enabled zsh's default prompt and disabled the shell integration. The commands entered still do not show up. Hm...

[no-integration.log](https://github.com/andre-simon/ansifilter/files/1556556/no-integation.log)

**Comment by agross** [comment]
This is the default iTerm2 output, all my shell config has been gone (i.e. zsh defaults). The command is also missing.

[default.log](https://github.com/andre-simon/ansifilter/files/1556704/default.log)

**Comment by andre-simon** [comment]
Hi, the parser is confused by [K and [?xxx sequences. I'll take a look. The latest push fixed the output of bold man headers line NAME and SYNOPSIS.

**Comment by agross** [comment]
Thank you! I wondered myself why these strange escapes show up in the log. I suspected my dotfiles, but given that I disabled them by removing `~/.zshrc` I am a bit at a loss.

**Comment by agross** [comment]
I just compiled master and tested with iTerm2 shell integration disabled. See attached results. There's an additional line break after `$`, but otherwise it looks good.


[test.log](https://github.com/andre-simon/ansifilter/files/1559659/test.log)

**Comment by andre-simon** [comment]
The newlines are fixed.

**Comment by agross** [comment]
Many thanks!
