### ISSUE TITLE
Chocolatey package

### ISSUE THREAD

**Issue by majkinetor** [andre-simon/ansifilter#14]
I want to create a chocolatey package for this similar to other ones I do here:

https://gist.github.com/majkinetor/a700c70b8847b29ebb1c918d47ee4eb1

I will embed binary without any other changes. Are you planning to re;ease binaries here or no ?

https://github.com/majkinetor/au-packages/issues/64

**Comment by andre-simon** [comment]
I will release binaries here: http://www.andre-simon.de/zip/download.php
The paths of the uploaded files only differ in the version part.
It's a bit cumbersome to upload it on several places.

The package will be linked on my download page when available.

**Comment by majkinetor** [comment]
Thanks.
