### ISSUE TITLE
make dll for windows

### ISSUE THREAD

**Issue by molchanov1983** [andre-simon/ansifilter#2]
Hello
I am looking for php script that allow me to clean ansi color from putty terminal output and your tool looks like right choise .
Question: Is it possible to make dll for apache 2.4 php 7?
Thanks

**Comment by andre-simon** [comment]
Hi,
most likely it is possible (there are no dependencies to take care of), but what about invoking the binary with a [pipe](https://github.com/andre-simon/highlight/blob/master/examples/highlight_pipe.php) in the script?

**Comment by molchanov1983** [comment]
Hello. Thanks for your response. 
My php code :
$descriptorSpec = array(
	0 => ['pipe', 'r'],
	1 => $this->_settings['tmpOutputFile'],
	2 => $this->_settings['tmpErrFile'],
);   
$this->_process = proc_open('C:/plink.exe -ssh $user@$ip", $descriptorSpec,$this->_pipes, $cwd, $env, $options);

And after i send some command to remote IP and read output from $this->_settings['tmpOutputFile']
where i have colors that i want to trim
Right now i use https://github.com/sensiolabs/ansi-to-html but it works incorrect sometimes (and as i see it is already not under developing) thats why i am looking for another way how to trim ansi color and found your repository. I would have dll ( this is the simplest way for me ) just add dll and call function inside php code when i need it
Thanks

**Comment by andre-simon** [comment]
You can invoke ansifilter just like plink:

```php
	//$ansi_input = content of  $this->_settings['tmpOutputFile']
	
	$descriptorspec = array(
		0 => array("pipe", "r"),
		1 => array("pipe", "w")
	);
	
	$process = proc_open("ansifilter.exe -f -H", $descriptorspec, $pipes);
	if (is_resource($process)) {
		fwrite($pipes[0], $ansi_input);
		fclose($pipes[0]);
		$html_output = stream_get_contents($pipes[1]);
		fclose($pipes[1]);
		// It is important that you close any pipes before calling
		// proc_close in order to avoid a deadlock
		proc_close($process);
		
		// -> $html_output contains HTML
	}
```

This should be way easier than including a DLL and dealing with its API.

**Comment by molchanov1983** [comment]
Thanks. Will try next week

**Comment by molchanov1983** [comment]
Thanks for your helping again
Now i faced another issue. I am able to fix it on php side but before doing it i want to make sure if it is not possible to do on ansifilter.exe side.
http://prntscr.com/f0nt32

I send string "test" (length - 4) to exe file and got "testCRLF" string (length = 6)
Thanks

**Comment by andre-simon** [comment]
Great news it works so far. Currently the exe always outputs a newline at the end.

**Comment by andre-simon** [comment]
The version 2.5 has an option --no-trailing-nl to omit he last newline.
