### ISSUE TITLE
makefile problem

### ISSUE THREAD

**Issue by tessus** [andre-simon/ansifilter#3]
It seems you have partly reverted my change and merged the CFLAGS into CXXFLAGS and removed CFLAGS altogether.
This is a problem, because port systems can't add their own build variables now. There was a reason why I had CFLAGS and CXXFLAGS in the makefile. I asked for the merge of my Pull Request to not have to add a patch to the MacPorts build process. This would have worked perfectly until you removed it. Ok, I will open another PR to add an EXTRA_CXXFLAGS which is supposed to be for external build systems (same as the EXTRA_LDFLAGS).

Unfortunately now I have to wait again until you release a new version with the fixed makefile.

**Comment by tessus** [comment]
see my PR #4

**Comment by andre-simon** [comment]
Sorry, this must have been lost because of the Git migration.

**Comment by tessus** [comment]
no worries. thanks for the merge.
