### ISSUE TITLE
ansifilter 2.5 and 2.6 fails to build in Fedora 27 (devel)

### ISSUE THREAD

**Issue by rosset** [andre-simon/ansifilter#6]
full logs: https://paste.fedoraproject.org/paste/khHBdVWl2WOBKw2hRAsoxA

g++ -c -Wall -O2 -DNDEBUG -std=c++11  rtfgenerator.cpp -o rtfgenerator.o
make[1]: Leaving directory '/home/filiperosset/rpmbuild/my/ansifilter/ansifilter-2.6/src'
make[1]: Entering directory '/home/filiperosset/rpmbuild/my/ansifilter/ansifilter-2.6/src'
g++ -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld  arg_parser.o stringtools.o cmdlineoptions.o main.o platform_fs.o codegenerator.o htmlgenerator.o pangogenerator.o texgenerator.o latexgenerator.o rtfgenerator.o plaintextgenerator.o bbcodegenerator.o elementstyle.o stylecolour.o preformatter.o -o ansifilter
/usr/bin/ld: arg_parser.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: stringtools.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: cmdlineoptions.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: main.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: codegenerator.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: htmlgenerator.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: pangogenerator.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: texgenerator.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: latexgenerator.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: rtfgenerator.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: plaintextgenerator.o: relocation R_X86_64_32S against symbol `_ZTVN10ansifilter18PlaintextGeneratorE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: bbcodegenerator.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: elementstyle.o: relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: stylecolour.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: preformatter.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
make[1]: *** [makefile:23: ansifilter] Error 1
make[1]: Leaving directory '/home/filiperosset/rpmbuild/my/ansifilter/ansifilter-2.6/src'
make: *** [makefile:30: all] Error 2
erro: Status de saída de /var/tmp/rpm-tmp.D0STx5 inválido (%build)

Erros na construção do RPM:
    Status de saída de /var/tmp/rpm-tmp.D0STx5 inválido (%build)
[filiperosset@raw ansifilter]$ gcc -v
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,objc,obj-c++,fortran,ada,go,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --enable-libmpx --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 7.1.1 20170718 (Red Hat 7.1.1-6) (GCC) 
[filiperosset@raw ansifilter]$

**Comment by andre-simon** [comment]
Hi, most possibly this is caused by settings in /usr/lib/rpm/redhat/redhat-hardened-ld. You can edit src/makefile and add -fPIC to CXXFLAGS: `CXXFLAGS= -Wall -O2 -DNDEBUG -std=c++11 -fPIC`

Maybe this applies: https://wiki.debian.org/Hardening#gcc_-pie_-fPIE

**Comment by rosset** [comment]
great, it did the trick, can you please commit this change for the next release? thanks.

cat ansifilter-fpic.patch 
--- src/makefile-orig	2017-07-26 23:09:39.568145865 -0300
+++ src/makefile	2017-07-27 20:18:36.968458950 -0300
@@ -6,7 +6,7 @@
 CC=g++
 
 # Added -std=c++11 because of auto_ptr to unique_ptr transition
-CXXFLAGS= -Wall -O2 -DNDEBUG -std=c++11
+CXXFLAGS= -Wall -O2 -DNDEBUG -std=c++11 -fPIC
 
 LDFLAGS=
